quarkus.http.access-log.enabled=true
quarkus.http.record-request-start-time=true
quarkus.http.access-log.pattern=%{REQUEST_LINE} %{RESPONSE_CODE} %Dms

%dev.quarkus.hibernate-orm.database.generation=drop-and-create
%dev.quarkus.hibernate-orm.log.sql=true

kafka.bootstrap.servers=localhost:9092

mp.messaging.outgoing.post-created-out.connector=smallrye-kafka
mp.messaging.outgoing.post-created-out.topic=post-created
mp.messaging.outgoing.post-created-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
